#!/bin/bash

set -e -x

vps_name=${1:-oracle_vps}

ssh $vps_name <<EOF
cd sunblock && git pull

pushd front
npm i
npm run build
popd

pushd back
npm i
popd

sudo systemctl daemon-reload
sudo systemctl stop sunblock-back
sudo systemctl start sunblock-back
sudo systemctl status sunblock-back
EOF
